accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns=[
    path('register',views.register,name="register"),
    path('login',views.login,name="login"),
    path('logout',views.logout,name="logout"),

]

blog/urls.py
from django.urls import path
from . import views


app_name='blog'
urlpatterns=[
    path('BlogAdd',views.BlogAdd,name='BlogAdd'),
    path('',views.home,name='home'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),

]

myblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('accounts.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
import datetime

from django.db import models

# Create your models here.
class BlogData(models.Model):
    hedding=models.CharField(max_length=100)
    content=models.CharField(max_length=1000)
    auther=models.CharField(max_length=100)
    date=models.DateTimeField(default=datetime.date.today())
    img=models.ImageField(upload_to='images',blank=True)

    def __str__(self):
        return self.hedding

blog/forms.py
from . models import BlogData
from django import forms
class Blogform(forms.ModelForm):
    class Meta:
        model=BlogData
        fields=['hedding','content','auther','date']

accounts/views.py
from django.contrib import messages

from django.shortcuts import render,redirect
from django.contrib.auth.models import auth,User
# Create your views here.
def login(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]

        user=auth.authenticate(username=username,password=password)
        if user is not None:

            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid creadentials')

            return redirect ('login')

    else:

        return render(request,"login.html")
def register(request):
    if request.method=="POST":

        username=request.POST["username"]
        first_name=request.POST["first_name"]
        last_name=request.POST["last_name"]
        email1=request.POST["email"]
        pswd1=request.POST["pswd1"]
        pswd2=request.POST["pswd2"]
        if pswd1==pswd2:
            # # if User.objects.filter(username=username).exist():
            #     messages.info(request, "username already taken")
            #     return redirect(register)
            # else:

                user=User.objects.create_user(first_name=first_name,last_name=last_name,email=email1,password=pswd1,username=username)
                user.save();
                print("user created")
        else:
            messages.info(request,"password didint mach")
            return redirect(register)
        return redirect("/")
    else:



        return render(request,'registration.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import BlogData
from . forms import Blogform
# Create your views here.
def BlogAdd(request):
    if request.method=='POST':
        hedding=request.POST.get('hedding')
        content=request.POST.get('content')
        date=request.POST.get('date')
        auther=request.POST.get('auther')
        img=request.POST.get('image')
        obj=BlogData(hedding=hedding,content=content,date=date,auther=auther,img=img)
        obj.save()
    obj1=BlogData.objects.all()
    return render(request, 'about.html', {'obj1': obj1})
    # return HttpResponse("hello")

def home(request):
    return render(request, 'index.html')


def delete(request,id):

    task=BlogData.objects.get(id=id)
    if request.method == 'POST':
        task.delete()
        return redirect ('blog:BlogAdd')
    return render(request,'delete.html',{'task':task})
def update(request,id):
    task=BlogData.objects.get(id=id)
    form=Blogform(request.POST or None,instance=task )
    if form.is_valid():
        form.save()
        return redirect('blog:BlogAdd')
    return render(request,'edit.html',{'task':task,'form':form})

templates/about.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}
            <div class="tm-col-left">
            <form method="post"  class="p-3 shadow">

    {% csrf_token %}
    <input type="text" name="hedding" class="form-control" placeholder="Blog heading"><br>
                <textarea name="content" class="form-control" placeholder="Write Your blog Here.."></textarea><br>
                    <input type="text" name="auther" class="form-control" placeholder="Auther name"><br>


                   <input type="date" name="date" class="form-control"><br>

    <input type="submit" class="btn btn-success" value="submit">
</form>
        </div>

            
            <div class="tm-row">
                <div class="tm-col-left"></div>
                <main class="tm-col-right">
                    <section class="tm-content tm-about">
                        {% for i in obj1 %}
                        <h2 class="mb-5 tm-content-title">{{ i.hedding}}</h2>
                        <hr class="mb-4">
                        <div class="media my-3">

                            <div class="media-body">
                                <p>{{i.content}}.</p>
                                <br><p>{{i.auther}}</p>

                                <a class="btn btn-danger" href="{% url  'blog:delete' i.id  %}">delete</a>
                                <a class="btn btn-success" href="{% url  'blog:update' i.id  %}">edit</a>

                                {% endfor %}
                            </div> 
                        </div>
<!--                        <div class="media my-3">-->
<!--                            <i class="fas fa-draw-polygon fa-3x p-3 mr-4"></i>-->
<!--                            <div class="media-body">-->
<!--                                <p>Nunc id hendrerit nunc. Etiam ultricies arcu sem, vel dapibus lacus lacinia quis. Nunc auctor placerat nisi ac ultrices.</p>-->
<!--                            </div> -->
<!--                        </div>-->
<!--                        <div class="media my-3">-->
<!--                            <i class="fab fa-creative-commons-share fa-3x p-3 mr-4"></i>-->
<!--                            <div class="media-body">-->
<!--                                <p>Vestibulum imperdiet hendrerit nibh. Integer sit amet lacus et nunc auctor tincidunt eu ac sapien. Ut suscipit velit eget faucibus finibus.</p>-->
<!--                            </div> -->
<!--                        </div>-->
<!--                        <div class="media my-3">-->
<!--                            <i class="fas fa-bookmark fa-3x p-3 mr-4"></i>-->
<!--                            <div class="media-body">-->
<!--                                <p>Prasent eget enim vitae sapien egestas aliquet non quis neque. Duis pharetra varius massa, ut bibendum tortor sodales ac.</p>-->
<!--                            </div> -->
<!--                        </div>                        -->
                    </section>
                </main>
            </div>


         {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>my kindom</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" /> <!-- https://fonts.google.com/ -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" /> <!-- https://getbootstrap.com/ -->
    <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet" /> <!-- https://fontawesome.com/ -->
    <link href="{% static 'css/templatemo-diagoona.css' %}" rel="stylesheet " />
<!--

TemplateMo 550 Diagoona

https://templatemo.com/tm-550-diagoona

-->
</head>

<body>
    <div class="tm-container">
        <div>
            <div class="tm-row pt-4">
                <div class="tm-col-left">
                    <div class="tm-site-header media">
                        <i class="fas fa-umbrella-beach fa-3x mt-1 tm-logo"></i>
                        <div class="media-body">
                            <h1 class="tm-sitename text-uppercase">Kindom </h1>
                            <p class="tm-slogon">let think about that  !!!</p>
                        </div>
                    </div>
                </div>
                <div class="tm-col-right">
                    <nav class="navbar navbar-expand-lg" id="tm-main-nav">
                        <button class="navbar-toggler toggler-example mr-0 ml-auto" type="button"
                            data-toggle="collapse" data-target="#navbar-nav"
                            aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                            <span><i class="fas fa-bars"></i></span>
                        </button>
                        <div class="collapse navbar-collapse tm-nav" id="navbar-nav">
                            <ul class="navbar-nav text-uppercase">
                                                <li class="nav-item">
                                    <a class="nav-link tm-nav-link" href="{% url  'blog:BlogAdd' %}">Home</a>
                                </li>
<!--                                 {% if user.is_authenticated %}-->
<!--                                <li class="nav-item active">-->
<!--                                    <a class="nav-link tm-nav-link" href="{% url 'accounts:logout' %}">logout</a>-->
<!--                                </li>-->
<!--                                  <li class="nav-item active">-->
<!--                                    <a class="nav-link tm-nav-link" href="">hi {{user.username}}</a>-->
<!--                                </li>-->
<!--                                {% else %}-->
<!--                                <li class="nav-item">-->
<!--                                    <a class="nav-link tm-nav-link" href="{% url 'accounts:register' %}">signin</a>-->
<!--                                </li>-->
<!--                                <li class="nav-item">-->
<!--                                    <a class="nav-link tm-nav-link"  href="{% url 'accounts:login' %}">login</a>-->
<!--                                </li>-->
<!--                                {% endif %}-->

                                {% if user.is_authenticated %}

            <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                <li class="nav-item active" ><a style="font-color:white">Hai {{user.username}}</a></li>
        {% else %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register' %}">signup</a></li>

            <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
        {% endif %}

                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>

            {% block content %}
            {% endblock %}




            <div class="tm-row">
            <div class="tm-col-left text-center">
                <ul class="tm-bg-controls-wrapper">
                    <li class="tm-bg-control active" data-id="0"></li>
                    <li class="tm-bg-control" data-id="1"></li>
                    <li class="tm-bg-control" data-id="2"></li>
                </ul>
            </div>
            <div class="tm-col-right tm-col-footer">
                <footer class="tm-site-footer text-right">
                    <p class="mb-0">Copyright 2021 Zndn Co.

                    | Design: <a rel="nofollow" target="_parent" href="" class="tm-text-link">zain's</a></p>
                </footer>
            </div>
        </div>

        <!-- Diagonal background design -->
        <div class="tm-bg">
            <div class="tm-bg-left"></div>
            <div class="tm-bg-right"></div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.4.1.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.backstretch.min.js' %} "></script>
    <script src="{% static 'js/templatemo-script.js' %}"></script>
</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Diagoona Template - Contact page</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" /> <!-- https://fonts.google.com/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet" /> <!-- https://getbootstrap.com/ -->
    <link href="fontawesome/css/all.min.css" rel="stylesheet" /> <!-- https://fontawesome.com/ -->
    <link href="css/templatemo-diagoona.css" rel="stylesheet" />
<!--

TemplateMo 550 Diagoona

https://templatemo.com/tm-550-diagoona

-->
</head>
<body>
    <div class="tm-container">
        <div>
            <div class="tm-row pt-4">
                <div class="tm-col-left">
                    <div class="tm-site-header media">
                        <i class="fas fa-umbrella-beach fa-3x mt-1 tm-logo"></i>
                        <div class="media-body">
                            <h1 class="tm-sitename text-uppercase">Kindom </h1>
                            <p class="tm-slogon">let think about that  !!!</p>
                        </div>        
                    </div>
                </div>
                <div class="tm-col-right">
                    <nav class="navbar navbar-expand-lg" id="tm-main-nav">
                        <button class="navbar-toggler toggler-example mr-0 ml-auto" type="button" 
                            data-toggle="collapse" data-target="#navbar-nav" 
                            aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                            <span><i class="fas fa-bars"></i></span>
                        </button>
                        <div class="collapse navbar-collapse tm-nav" id="navbar-nav">
                            <ul class="navbar-nav text-uppercase">
                                               <li class="nav-item">
                                    <a class="nav-link tm-nav-link" href="{% url  'blog:BlogAdd' %}">Home</a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link tm-nav-link" href="about.html">login<span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link tm-nav-link" href="services.html">logout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link tm-nav-link" href="contact.html">sign in</a>
                                </li>
                            </ul>                            
                        </div>                        
                    </nav>
                </div>
            </div>
            
            <div class="tm-row">
                <div class="tm-col-left"></div>
                <main class="tm-col-right tm-contact-main"> <!-- Content -->
                    <section class="tm-content tm-contact">
                        <h2 class="mb-4 tm-content-title">Contact Us</h2>
                        <p class="mb-85">Etiam et egestas arcu. Fusce congue quis elit vitae commodo. Cras neque mauris, vehicula in ipsum sit amet, faucibus aliquam arcu.</p>
                        <form id="contact-form" action="" method="POST">
                            <div class="form-group mb-4">
                                <input type="text" name="name" class="form-control" placeholder="Name" required="" />
                            </div>
                            <div class="form-group mb-4">
                                <input type="email" name="email" class="form-control" placeholder="Email" required="" />
                            </div>
                            <div class="form-group mb-5">
                                <textarea rows="6" name="message" class="form-control" placeholder="Message..." required=""></textarea>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-big btn-primary">Send It</button>
                            </div>
                        </form>
                    </section>
                </main>
            </div>
        </div>        

        <div class="tm-row">
            <div class="tm-col-left text-center">            
                <ul class="tm-bg-controls-wrapper">
                    <li class="tm-bg-control active" data-id="0"></li>
                    <li class="tm-bg-control" data-id="1"></li>
                    <li class="tm-bg-control" data-id="2"></li>
                </ul>            
            </div>        
            <div class="tm-col-right tm-col-footer">
                <footer class="tm-site-footer text-right">
                    <p class="mb-0">Copyright 2020 Diagoona Co. 
                    
                    | Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-text-link">TemplateMo</a></p>
                </footer>
            </div>  
        </div>

        <div class="tm-bg"> <!-- Diagonal background design -->
            <div class="tm-bg-left"></div>
            <div class="tm-bg-right"></div>
        </div>
    </div>

    <script src="js/jquery-3.4.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.backstretch.min.js"></script>
    <script src="js/templatemo-script.js"></script>
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br><br>

    <div>
        <div>
            <form method="post">
                {% csrf_token %}
    <h4>ARE YOU SURE, YOU WANT TO DELETE !!!!</h4>
    <br><br>
    <button class="btn btn-danger" type="submit">confirm</button>
</form>
        </div>
    </div>




      <br>
      <br>
      <br>
      <br>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}

               <div class="tm-col-left">
            <form method="post"  class="p-3 shadow">

    {% csrf_token %}
                <div>
                {{ form.as_p }}
            </div>


    <input type="submit" class="btn btn-success" value="submit">
</form>
        </div>



{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->

<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--    <title>Diagoona HTML CSS Template</title>-->
<!--    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet" /> &lt;!&ndash; https://fonts.google.com/ &ndash;&gt;-->
<!--    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" /> &lt;!&ndash; https://getbootstrap.com/ &ndash;&gt;-->
<!--    <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet" /> &lt;!&ndash; https://fontawesome.com/ &ndash;&gt;-->
<!--    <link href="{% static 'css/templatemo-diagoona.css' %}" rel="stylesheet " />-->
<!--&lt;!&ndash;-->

<!--TemplateMo 550 Diagoona-->

<!--https://templatemo.com/tm-550-diagoona-->

<!--&ndash;&gt;-->
<!--</head>-->

<!--<body>-->
<!--    <div class="tm-container">        -->
<!--        <div>-->
<!--            <div class="tm-row pt-4">-->
<!--                <div class="tm-col-left">-->
<!--                    <div class="tm-site-header media">-->
<!--                        <i class="fas fa-umbrella-beach fa-3x mt-1 tm-logo"></i>-->
<!--                        <div class="media-body">-->
<!--                            <h1 class="tm-sitename text-uppercase">Kindom </h1>-->
<!--                            <p class="tm-slogon">let think about that  !!!</p>-->
<!--                        </div>        -->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="tm-col-right">-->
<!--                    <nav class="navbar navbar-expand-lg" id="tm-main-nav">-->
<!--                        <button class="navbar-toggler toggler-example mr-0 ml-auto" type="button" -->
<!--                            data-toggle="collapse" data-target="#navbar-nav" -->
<!--                            aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">-->
<!--                            <span><i class="fas fa-bars"></i></span>-->
<!--                        </button>-->
<!--                        <div class="collapse navbar-collapse tm-nav" id="navbar-nav">-->
<!--                            <ul class="navbar-nav text-uppercase">-->
<!--                                                <li class="nav-item">-->
<!--                                    <a class="nav-link tm-nav-link" href="{% url  'blog:BlogAdd' %}">Home</a>-->
<!--                                </li>-->
<!--                                 {% if user.is_authenticated %}-->
<!--                                <li class="nav-item active">-->
<!--                                    <a class="nav-link tm-nav-link" href="{% url 'accounts:logout' %}">logout</a>-->
<!--                                </li>-->
<!--                                  <li class="nav-item active">-->
<!--                                    <a class="nav-link tm-nav-link" href="">hi {{user.username}}</a>-->
<!--                                </li>-->
<!--                                {% else %}-->
<!--                                <li class="nav-item">-->
<!--                                    <a class="nav-link tm-nav-link" href="{% url 'accounts:register' %}">signin</a>-->
<!--                                </li>-->
<!--                                <li class="nav-item">-->
<!--                                    <a class="nav-link tm-nav-link"  href="{% url 'accounts:login' %}">login</a>-->
<!--                                </li>-->
<!--                                {% endif %}-->
<!--                            </ul>                            -->
<!--                        </div>                        -->
<!--                    </nav>-->
<!--                </div>-->
<!--            </div>-->
<!--            -->
            {% block content %}
            <div class="tm-row">
                <div class="tm-col-left"></div>
                <main class="tm-col-right">
                    <section class="tm-content">
                        <h2 class="mb-5 tm-content-title"></h2>
                        <p class="mb-5 tm-content-title">"I didn't fail the test. I just found 100 ways to do it wrong"</p>
                        <p class="mb-5">                                      --Benjamin Franklin</p>
                        <hr class="mb-5"><br><br><br><br>
<!--                        <p class="mb-5">ges auto play settings (true or false in line number 33) in templatemo-script.js file in js folder.</p>                        -->
                        <a href="{% url 'blog:BlogAdd' %}" class="btn btn-primary">Continue...</a>
                    </section>
                </main>
            </div>
  {% endblock %}



<!--        <div class="tm-row">-->
<!--            <div class="tm-col-left text-center">            -->
<!--                <ul class="tm-bg-controls-wrapper">-->
<!--                    <li class="tm-bg-control active" data-id="0"></li>-->
<!--                    <li class="tm-bg-control" data-id="1"></li>-->
<!--                    <li class="tm-bg-control" data-id="2"></li>-->
<!--                </ul>            -->
<!--            </div>        -->
<!--            <div class="tm-col-right tm-col-footer">-->
<!--                <footer class="tm-site-footer text-right">-->
<!--                    <p class="mb-0">Copyright 2020 Diagoona Co. -->
<!--                    -->
<!--                    | Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-text-link">TemplateMo</a></p>-->
<!--                </footer>-->
<!--            </div>  -->
<!--        </div>-->

<!--        &lt;!&ndash; Diagonal background design &ndash;&gt;-->
<!--        <div class="tm-bg">-->
<!--            <div class="tm-bg-left"></div>-->
<!--            <div class="tm-bg-right"></div>-->
<!--        </div>-->
<!--    </div>-->

<!--    <script src="{% static 'js/jquery-3.4.1.min.js' %} "></script>-->
<!--    <script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<!--    <script src="{% static 'js/jquery.backstretch.min.js' %} "></script>-->
<!--    <script src="{% static 'js/templatemo-script.js' %}"></script>-->
<!--</body>-->
<!--</html>-->

templates/login.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}

 <div class="tm-col-left">

                      <form method="post"  class="p-3 shadow">

    {% csrf_token %}
    <input type="text" name="username" class="form-control" placeholder="Your username"><br>
               <input type="password" name="password" class="form-control" placeholder="Enter password"><br><br>

    <input type="submit" class="btn btn-success" value="login">
</form>
 </div>
         {% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}

            <div class="tm-row">
                <div class="tm-col-left">

                          <form method="post"  class="p-3 shadow">

    {% csrf_token %}
 username
    <input type="text" placeholder="username" class="form-control" name="username" > <br>  <br>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" class="form-control" name="email" id="email" required>
    <br>  <br>


      <label ><b>name</b></label>
    <input type="text" placeholder="first name" class="form-control" name="first_name"  > <br>  <br>


    <label ><b>last name</b></label>
    <input type="text" placeholder="last name" class="form-control" name="last_name" > <br>  <br>



    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" class="form-control" name="pswd1" id="psw" required> <br>  <br>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" class="form-control" name="pswd2" id="psw-repeat" required>  <br>  <br>
                               <button type="submit" class="registerbtn">Register</button>
</form>

            </div>
            </div>
 {% endblock %}